### ISSUE TITLE
New course incoming ??

### ISSUE THREAD

**Issue by SteveSayantan** [john-smilga/react-testing-course#1]
Hey John,
sorry for this approach but I'm really curious to know if this is going to be a part of your react course. I've been struggling (or, running like a headless chicken) to find a structured, latest resource for react testing as there are very few available on the internet. Thanks for being a life-saver as always. I've learnt both react and node from your courses and seeing this repo, I couldn't help asking. Thanks again. 😇

**Comment by john-smilga** [comment]
Yes, I’m recording a new course and will add some parts of it, to the existing React Course soon. 😊
